### ISSUE TITLE
你好，有相关的讲义pdf吗，我想参考一下

### ISSUE THREAD

**Issue by dzwduan** [Kepler-Duo/xv6#1]

**Comment by Kepler-Duo** [comment]
[xv6操作系统实验-2021-01-28-3.pdf](https://github.com/Kepler-Duo/xv6/files/8878218/xv6.-2021-01-28-3.pdf)

**Comment by Kepler-Duo** [comment]
thread实验在第11章

**Comment by dzwduan** [comment]
非常感谢
